# Generated by Django 4.2.5 on 2024-09-15 08:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст заявки')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть введен в формате: '+799999999'. Допускается не более 11 цифр.", regex='^\\+?7?\\d{10}$')], verbose_name='Телефон')),
                ('e_mail', models.EmailField(max_length=200, verbose_name='Электронный адрес')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик услуги')),
                ('order', models.ForeignKey(blank=True, help_text='Выберите заказ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='posts.order', verbose_name='Заказ')),
                ('project_mng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_mng', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WAIT', 'Ожидание'), ('START', 'Старт'), ('INITIAL', 'Интервью'), ('TZ', 'Техническое задание'), ('PROJECT', 'Проект'), ('DESIGN', 'Дезайн'), ('DEVELOP', 'Разработка'), ('TEST', 'Тестирование'), ('STARTUP', 'Запуск продукта'), ('MAINTAIN', 'Техническая поддержка'), ('FINISH', 'Проект закрыт')], max_length=21)),
                ('description', models.TextField()),
                ('prev_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='posts.status')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала этапа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания этапа')),
                ('process_mng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_mng', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.status')),
            ],
            options={
                'ordering': ('-project',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ManyToManyField(through='posts.Workflow', to='posts.status'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='start_date_before_end_date'),
        ),
    ]
